services:
  backend:
    working_dir: /app
    networks:
      - mynet
    ports:
      - 8000:8080
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-pguser}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-pgdb}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    networks:
      - mynet
    depends_on:
      - backend

  db:
    image: postgres:17
    restart: always
    networks:
      - mynet
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password not set}
      POSTGRES_DB: ${POSTGRES_DB:-pgdb}
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  mynet:
    driver: bridge