name: Backend CI

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**', '.github/workflows/backend-ci.yml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'backend/**', '.github/workflows/backend-ci.yml' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/backend
  
jobs:
  lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Go Format
        run: gofmt -s -w .
        working-directory: ./backend

      - name: Go Vet
        run: go vet ./...
        working-directory: ./backend

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout 5m
          working-directory: ./backend


  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Test
      run: go test -v ./...
      working-directory: ./backend

    - name: Build
      run: go build -v ./...
      working-directory: ./backend


  docker-build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test-and-build]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}            
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max